/**
 * Shared email scraping utility.
 * Scrapes websites and extracts email addresses.
 * Used by hr.component (API) and exelScrapingRoute (Google Sheets sync).
 *
 * Only extracts emails from: (1) explicit mailto: links in the HTML, (2) visible text in the website's raw HTML
 * (homepage, footer, header, contact pages). No JSON-LD or script content—only mailto and visible page source.
 * Scans: trusted sections (footer/header/contact), full page-source (visible HTML), then domain filter.
 * Only return emails that: valid syntax; match website domain; appear on the page (no inferred addresses).
 * Ignore: image filenames; internal aliases; random codes. Normalize duplicates; include verifiedCount.
 * If emails exist but require JS rendering → output: "Emails present but require JS rendering".
 * For JS-rendered or captcha-protected sites (e.g. upkeepdxb.com): when static fetch finds no email,
 * browser automation is used: Playwright is tried first for captcha/challenge sites, then Puppeteer as fallback.
 */

const https = require("https");
const http = require("http");
const zlib = require("zlib");
const cheerio = require("cheerio");

const FLEXIBLE_EMAIL_PATTERN = /[A-Za-z0-9._%+-]{1,64}@[A-Za-z0-9.-]{1,255}\.[A-Za-z]{2,}/g;
const FINAL_EMAIL_VALIDATION = /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/;
const TRAILING_WORDS = ["chat", "click", "email", "mail", "contact", "send", "message"];
const FALSE_POSITIVES = [
  "example.com", "test@example", "your-email", "email@example",
  "admin@localhost", "sentry.io", "wixpress.com", "u002f@", "u00", "http", "www.",
];

/** Local parts that indicate autogenerated / non-official contact emails - exclude these */
const AUTOGENERATED_LOCAL_PARTS = [
  "noreply", "no-reply", "donotreply", "donotreplay", "do-not-reply", "do_not_reply",
  "mailer-daemon", "mailerdaemon", "postmaster", "mail-delivery", "maildelivery",
  "sentry", "gitlab", "jenkins", "git", "ci", "build", "root", "daemon",
  "bounce", "bounces", "notifications", "nobody", "hostmaster",
];

/** Domains/patterns indicating internal branch or local office - exclude these */
const INTERNAL_DOMAIN_PATTERNS = [
  /\.local$/i, /\.local\./i, /\.internal$/i, /\.internal\./i, /\.lan$/i, /\.corp$/i, /\.localdomain$/i,
  /localhost/i, /^127\./, /^10\./, /^192\.168\./, /^172\.(1[6-9]|2[0-9]|3[0-1])\./,
  /-internal\./i, /\.internal\./i,
];

/** Local part format: 3-4 letter branch/location code + 2 digits = internal alias (e.g. izm51, ist42, ank44) */
const INTERNAL_BRANCH_LOCAL_PATTERN = /^[a-z]{3,4}\d{2}$/;

/** Domain ending in file extensions = false positive (e.g. be_a_part_of_it@3x.jpg) */
const FILE_EXTENSION_TLD = /\.(jpg|jpeg|png|gif|svg|webp|pdf|ico|bmp)$/i;

/** Local parts that look like tracking strings or random codes - exclude */
const TRACKING_LOCAL_PATTERNS = [
  /^utm_/i, /^ga_/i, /^gclid/i, /^fbclid/i, /^_[a-z0-9]{12,}$/i,
  /^[a-f0-9]{24,}$/i, /^tracking/i, /^pixel/i,
];

/** Trusted section selectors - check every visible section: Footer, Header, Sidebar, Contact, Support, Booking */
const TRUSTED_SECTION_SELECTORS = [
  "footer", "header", "nav", "aside",
  "[role='contentinfo']", "[role='navigation']", "[role='complementary']",
  "[class*='footer']", "[id*='footer']", "[class*='Footer']",
  "[class*='header']", "[id*='header']", "[class*='Header']",
  "[class*='sidebar']", "[id*='sidebar']", "[class*='Sidebar']",
  "[class*='contact']", "[id*='contact']", "[class*='Contact']",
  "[class*='iletisim']", "[class*='kontakt']", "[class*='contacto']", "[class*='bize-ulasin']",
  "[class*='about']", "[id*='about']", "[class*='About']",
  "[class*='hakkimizda']", "[class*='ueber-uns']", "[class*='qui-sommes-nous']",
  "[class*='support']", "[id*='support']", "[class*='Support']", "[class*='destek']",
  "[class*='booking']", "[id*='booking']", "[class*='Booking']", "[class*='rezervasyon']",
  "[class*='customer-service']", "[class*='customerservice']", "[class*='customer_service']",
  "[class*='reach']", "[class*='reach-us']",
  "[class*='imprint']", "[class*='impressum']", "[class*='legal']",
  "[class*='privacy']", "[class*='gizlilik']", "[class*='kvkk']", "[class*='datenschutz']",
  "[class*='office']", "[id*='office']", "[class*='Office']", "[class*='head-office']", "[class*='headoffice']",
  "[class*='contact-info']", "[class*='contactinfo']", "[class*='contact_info']", "[class*='contact-details']",
  "[class*='address']", "[id*='address']", "[class*='Address']",
  ".site-footer", ".page-footer", ".main-footer", ".site-header", ".main-nav",
  ".contact", ".about", ".support", ".sidebar", ".widget",
  // Elementor / PXL (e.g. "SEND US MAIL" blocks with <a href="mailto:..."><span>...</span></a>)
  "[class*='elementor-container']", "[class*='elementor-widget']", "[class*='elementor-column']",
  "[class*='pxl-link']", "[class*='pxl_link']", "[id*='pxl-link']", ".elementor-widget-container",
];

function decodeCloudflareEmail(hexStr) {
  if (!hexStr || typeof hexStr !== "string" || hexStr.length < 4) return null;
  const clean = hexStr.replace(/[^0-9a-fA-F]/g, "");
  if (clean.length < 4) return null;
  try {
    const key = parseInt(clean.slice(0, 2), 16);
    let email = "";
    for (let i = 2; i < clean.length; i += 2) {
      const byte = parseInt(clean.slice(i, i + 2), 16) ^ key;
      email += String.fromCharCode(byte);
    }
    return email.includes("@") ? email : null;
  } catch {
    return null;
  }
}

function decodeHtmlEntities(str) {
  if (!str || typeof str !== "string") return str;
  return str
    .replace(/&#64;/g, "@").replace(/&#x40;/gi, "@")
    .replace(/&#46;/g, ".").replace(/&#x2e;/gi, ".")
    .replace(/&#160;/g, " ").replace(/&nbsp;/gi, " ")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
}

/** Deobfuscate email text: info [at] domain [dot] com -> info@domain.com */
function deobfuscateEmailText(str) {
  if (!str || typeof str !== "string") return str;
  return str
    .replace(/\s*\[\s*at\s*\]\s*|\[at\]|\(at\)|\[AT\]|\(AT\)|\s+at\s+/gi, "@")
    .replace(/\s*\[\s*dot\s*\]\s*|\[dot\]|\(dot\)|\[\.\]|\(\.\)|\s+dot\s+/gi, ".")
    .replace(/\s*\{\s*at\s*\}\s*/gi, "@")
    .replace(/\s*\{\s*dot\s*\}\s*/gi, ".")
    .replace(/\s*<\s*at\s*>\s*/gi, "@")
    .replace(/\s*<\s*dot\s*>\s*/gi, ".")
    // Handle emails with spaces around @ and . : "enquiry @ exclusive-links . com" -> "enquiry@exclusive-links.com"
    .replace(/\s*@\s*/g, "@")
    .replace(/\s*\.\s*/g, ".");
}

/** Strip HTML comments, scripts, styles; return visible-only HTML string */
function stripNonVisibleHtml(html) {
  return (html || "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, "");
}

/** Extract emails from JSON-LD (schema.org Organization, LocalBusiness, etc.); returns Set of raw emails */
function extractEmailsFromJsonLd(htmlContent) {
  const emails = new Set();
  const ldJsonRegex = /<script[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = ldJsonRegex.exec(htmlContent)) !== null) {
    try {
      const jsonStr = match[1].trim();
      const data = JSON.parse(jsonStr);
      const walk = (obj) => {
        if (!obj || typeof obj !== "object") return;
        if (typeof obj.email === "string" && obj.email.includes("@")) {
          const m = obj.email.trim().match(FLEXIBLE_EMAIL_PATTERN);
          if (m) m.forEach((e) => emails.add(e));
        }
        if (Array.isArray(obj)) {
          obj.forEach(walk);
        } else {
          Object.values(obj).forEach(walk);
        }
      };
      walk(data);
    } catch (_) {}
  }
  return emails;
}

/** Extract emails from JavaScript (variables, strings); returns Set of raw emails */
function extractEmailsFromScripts(htmlContent) {
  const emails = new Set();
  const scriptRegex = /<script[\s\S]*?<\/script>/gi;
  const mailtoPattern = /mailto:([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})/gi;
  let scriptMatch;
  while ((scriptMatch = scriptRegex.exec(htmlContent)) !== null) {
    const decoded = decodeHtmlEntities(deobfuscateEmailText(scriptMatch[0]));
    (decoded.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
    let mt;
    mailtoPattern.lastIndex = 0;
    while ((mt = mailtoPattern.exec(decoded)) !== null) emails.add(mt[1]);
  }
  return emails;
}

/**
 * Extract emails from visible HTML, footer, contact sections, mailto links.
 * Returns { emails: Set, fromMailto: Set } - fromMailto = emails found in mailto: (confirmed in context)
 */
function extractEmailsFromTrustedSections(htmlContent) {
  const emails = new Set();
  const fromMailto = new Set();
  const visibleHtml = stripNonVisibleHtml(htmlContent);
  const decodedHtml = decodeHtmlEntities(visibleHtml);
  const deobfuscatedHtml = deobfuscateEmailText(decodedHtml);
  const mailtoPattern = /mailto:([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})/gi;

  try {
    const $ = cheerio.load(deobfuscatedHtml);

    // Remove script, style, noscript, svg, img - ignore non-visible and image names
    $("script, style, noscript, svg, img").remove();

    let trustedRoot = $(TRUSTED_SECTION_SELECTORS.join(", "));
    if (trustedRoot.length === 0) trustedRoot = $("body");

    trustedRoot.each((_, el) => {
      const $el = $(el);
      const html = $el.html() || "";
      const text = $el.text() || "";
      const decoded = decodeHtmlEntities(deobfuscateEmailText(html));
      const deobfuscatedText = deobfuscateEmailText(text);
      (decoded.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
      (text.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
      // Also check deobfuscated text (handles emails with spaces like "enquiry @ exclusive-links . com")
      (deobfuscatedText.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
      let m;
      mailtoPattern.lastIndex = 0;
      while ((m = mailtoPattern.exec(decoded)) !== null) {
        const em = m[1].toLowerCase();
        emails.add(em);
        fromMailto.add(em);
      }
    });
    
    // Also scan full body text as fallback (in case email is outside trusted sections but visible)
    const bodyText = $("body").text() || "";
    const deobfuscatedBodyText = deobfuscateEmailText(bodyText);
    (deobfuscatedBodyText.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));

    trustedRoot.find('a[href*="cdn-cgi/l/email-protection"]').each((_, el) => {
      const href = $(el).attr("href") || "";
      const hashMatch = href.match(/#([0-9a-fA-F]+)/);
      if (hashMatch) {
        const decoded = decodeCloudflareEmail(hashMatch[1]);
        if (decoded && decoded.includes("@")) emails.add(decoded);
      }
    });

    trustedRoot.find('a[href^="mailto:"]').each((_, el) => {
      let href = $(el).attr("href") || "";
      href = decodeHtmlEntities(href);
      const emailPart = href.replace(/^mailto:/i, "").split("?")[0].split("&")[0].trim();
      if (emailPart && emailPart.includes("@")) {
        const norm = emailPart.toLowerCase().match(FLEXIBLE_EMAIL_PATTERN)?.[0] || emailPart.toLowerCase();
        if (FINAL_EMAIL_VALIDATION.test(norm)) {
          emails.add(norm);
          fromMailto.add(norm);
        }
      }
    });

    // Also find mailto links anywhere in body (e.g. Elementor/pxl-link: <li><a href="mailto:info@totalfitdubai.com"><span>...</span></a></li>)
    $("body").find('a[href^="mailto:"]').each((_, el) => {
      let href = $(el).attr("href") || "";
      href = decodeHtmlEntities(href);
      const emailPart = href.replace(/^mailto:/i, "").split("?")[0].split("&")[0].trim();
      if (emailPart && emailPart.includes("@")) {
        const norm = emailPart.toLowerCase().match(FLEXIBLE_EMAIL_PATTERN)?.[0] || emailPart.toLowerCase();
        if (FINAL_EMAIL_VALIDATION.test(norm)) {
          emails.add(norm);
          fromMailto.add(norm);
        }
      }
    });

    const visibleOnly = stripNonVisibleHtml(htmlContent);
    const cfRegex = /cdn-cgi\/l\/email-protection#([0-9a-fA-F]+)/g;
    let cfMatch;
    while ((cfMatch = cfRegex.exec(visibleOnly)) !== null) {
      const decoded = decodeCloudflareEmail(cfMatch[1]);
      if (decoded && decoded.includes("@")) emails.add(decoded);
    }
  } catch (_) {
    const visibleOnly = stripNonVisibleHtml(htmlContent);
    const decoded = decodeHtmlEntities(deobfuscateEmailText(visibleOnly));
    (decoded.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
    let m;
    mailtoPattern.lastIndex = 0;
    while ((m = mailtoPattern.exec(decoded)) !== null) emails.add(m[1]);
  }

  return { emails, fromMailto };
}

/**
 * Fallback: extract from full visible body (no script/style) when trusted sections miss emails.
 * Gets all mailto: links and regex email matches from body. Used when trusted sections yield none.
 */
function extractEmailsFromFullBody(htmlContent) {
  const emails = new Set();
  const fromMailto = new Set();
  const visibleHtml = stripNonVisibleHtml(htmlContent);
  const decoded = decodeHtmlEntities(deobfuscateEmailText(visibleHtml));
  const mailtoPattern = /mailto:([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})/gi;
  (decoded.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
  // Also extract from text content (handles emails split across HTML elements)
  try {
    const $ = cheerio.load(visibleHtml);
    const bodyText = $("body").text() || "";
    const deobfuscatedBodyText = deobfuscateEmailText(bodyText);
    (deobfuscatedBodyText.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
  } catch (_) {}
  let m;
  mailtoPattern.lastIndex = 0;
  while ((m = mailtoPattern.exec(decoded)) !== null) {
    const em = m[1].toLowerCase();
    emails.add(em);
    fromMailto.add(em);
  }
  return { emails, fromMailto };
}

/**
 * Scan actual page source (visible HTML: no script/style/noscript) for emails that explicitly
 * appear in the HTML: all mailto: links and all email-like strings (e.g. in footer, header,
 * contact blocks, or attributes). Use in addition to trusted sections so nothing is missed.
 */
function extractEmailsFromPageSource(htmlContent) {
  const emails = new Set();
  const fromMailto = new Set();
  const visibleHtml = stripNonVisibleHtml(htmlContent);
  const decoded = decodeHtmlEntities(deobfuscateEmailText(visibleHtml));
  const mailtoPattern = /mailto:([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})/gi;
  (decoded.match(FLEXIBLE_EMAIL_PATTERN) || []).forEach((e) => emails.add(e));
  let m;
  mailtoPattern.lastIndex = 0;
  while ((m = mailtoPattern.exec(decoded)) !== null) {
    const em = m[1].toLowerCase();
    emails.add(em);
    fromMailto.add(em);
  }
  return { emails, fromMailto };
}

/**
 * Extract and classify emails from HTML. Scans actual page source (footer, header, contact pages,
 * and all crawled HTML) for emails that explicitly appear in the source or in mailto: links.
 * Combines: trusted sections (footer/header/contact selectors), full page-source scan, full-body fallback, JSON-LD.
 * @returns {{ verified: string[], rejected: Array<{ email: string, reason: string }>, loadedViaJs?: boolean }}
 */
function extractAndFilterEmails(htmlContent, websiteUrl) {
  let { emails: contextualEmails, fromMailto } = extractEmailsFromTrustedSections(htmlContent);

  // Always scan actual HTML content (page source) for mailto: and explicit email strings
  // so we don't miss emails in footer/header/contact or in attributes.
  const pageSource = extractEmailsFromPageSource(htmlContent);
  pageSource.emails.forEach((e) => contextualEmails.add(e));
  pageSource.fromMailto.forEach((e) => fromMailto.add(e));

  if (contextualEmails.size === 0) {
    const fallback = extractEmailsFromFullBody(htmlContent);
    fallback.emails.forEach((e) => contextualEmails.add(e));
    fallback.fromMailto.forEach((e) => fromMailto.add(e));
  }

  // Only mailto and visible HTML text are used for verified emails (no JSON-LD or script content)
  const jsEmails = extractEmailsFromScripts(htmlContent);

  const { verified, rejected } = filterAndClassifyEmails(
    [...contextualEmails],
    websiteUrl,
    fromMailto
  );

  let loadedViaJs = false;
  if (verified.length === 0 && jsEmails.size > 0) {
    const jsFiltered = filterAndClassifyEmails([...jsEmails], websiteUrl);
    if (jsFiltered.verified.length > 0) {
      loadedViaJs = true;
    }
  }

  return {
    verified,
    rejected,
    ...(loadedViaJs && { loadedViaJs: true, message: "Emails present but require JS rendering" }),
  };
}

/**
 * Get website domain from URL (strip www)
 */
function getWebsiteDomain(url) {
  try {
    const u = new URL(url);
    return (u.hostname || "").replace(/^www\./, "").toLowerCase();
  } catch {
    return "";
  }
}

/**
 * Check if email domain matches website domain (or subdomain).
 * Also treats "totalfitdubai.com" as matching site "thetotalfitdubai.com" (same brand, common "the" prefix).
 */
function emailDomainMatchesWebsite(emailDomain, websiteDomain) {
  if (!emailDomain || !websiteDomain) return false;
  const ed = emailDomain.toLowerCase();
  const wd = websiteDomain.toLowerCase();
  if (ed === wd || ed.endsWith("." + wd)) return true;
  // Same base: thetotalfitdubai.com vs totalfitdubai.com
  const wdBase = wd.replace(/^the\.?/, "");
  const edBase = ed.replace(/^the\.?/, "");
  return wdBase === edBase || ed.endsWith("." + wdBase);
}

/** Common public contact domains - allow when email is published on site (contact/footer/mailto) */
const PUBLIC_CONTACT_DOMAINS = [
  "gmail.com", "googlemail.com", "yahoo.com", "yahoo.co.uk", "outlook.com", "hotmail.com",
  "hotmail.co.uk", "live.com", "icloud.com", "me.com", "aol.com", "protonmail.com",
  "mail.com", "zoho.com", "yandex.com", "gmx.com", "gmx.net",
];

/** Domains that are template/designer footers on client sites - never return these when domain doesn't match */
const TEMPLATE_DOMAINS_BLOCKLIST = ["hadkaur.com"];

/**
 * Validate email as official public contact; returns { valid: boolean, reason?: string }
 * @param {string} websiteUrl - Used to validate domain match
 * @param {boolean} fromMailtoInContext - If true, allow branch emails (confirmed on page)
 */
function validateOfficialContactEmail(email, websiteUrl, fromMailtoInContext = false) {
  if (!email || !email.includes("@")) return { valid: false, reason: "Invalid format" };
  const emailLower = email.toLowerCase();
  const [local, domain] = emailLower.split("@");
  if (!local || !domain) return { valid: false, reason: "Invalid format" };

  if (FILE_EXTENSION_TLD.test(domain))
    return { valid: false, reason: "Image or file name (.jpg, .png, .svg)" };
  if (FALSE_POSITIVES.some((fp) => emailLower.includes(fp)))
    return { valid: false, reason: "Known false positive" };
  if (TRACKING_LOCAL_PATTERNS.some((p) => p.test(local)))
    return { valid: false, reason: "Tracking string or random code" };

  if (!fromMailtoInContext) {
    if (INTERNAL_BRANCH_LOCAL_PATTERN.test(local))
      return { valid: false, reason: "Auto-generated location email (not confirmed on page)" };
  }

  if (emailLower.startsWith("u") && local.length < 3)
    return { valid: false, reason: "Invalid local part" };

  const localBase = local.replace(/[^a-z]/g, "");
  if (AUTOGENERATED_LOCAL_PARTS.some((bad) => local === bad || localBase === bad.replace(/[-_]/g, "")))
    return { valid: false, reason: "Autogenerated or system email (noreply, postmaster, etc.)" };
  if (AUTOGENERATED_LOCAL_PARTS.some((bad) => local.startsWith(bad + ".") || local.startsWith(bad + "-") || local.startsWith(bad + "_")))
    return { valid: false, reason: "Autogenerated or system email" };
  if (INTERNAL_DOMAIN_PATTERNS.some((p) => p.test(domain)))
    return { valid: false, reason: "Internal or local domain (.local, .internal, localhost)" };

  // When email is from mailto link or contact section (fromMailtoInContext), allow it even if domain differs
  if (fromMailtoInContext) {
    if (TEMPLATE_DOMAINS_BLOCKLIST.includes(domain))
      return { valid: false, reason: "Template/designer domain on client site" };
    return { valid: true };
  }

  if (websiteUrl) {
    const websiteDomain = getWebsiteDomain(websiteUrl);
    const domainOk =
      emailDomainMatchesWebsite(domain, websiteDomain) ||
      PUBLIC_CONTACT_DOMAINS.includes(domain);
    if (websiteDomain && !domainOk) {
      if (TEMPLATE_DOMAINS_BLOCKLIST.includes(domain))
        return { valid: false, reason: "Template/designer domain on client site" };
      // Allow contact emails on page that use a different domain (e.g. upkeep@aaronz.co on upkeepdxb.com)
      return { valid: true };
    }
  }

  return { valid: true };
}

function normalizeEmail(email) {
  let emailClean = (email || "").trim();
  const m = emailClean.match(FLEXIBLE_EMAIL_PATTERN);
  if (m) emailClean = m[0];
  if (!emailClean.includes("@")) return null;
  let [, local, domain] = emailClean.match(/^(.+?)@(.+)$/) || [];
  if (!local || !domain) return null;
  const stripLeadingDigits = local.match(/^\d{4,}([a-zA-Z][a-zA-Z0-9._%+-]*)$/);
  if (stripLeadingDigits) local = stripLeadingDigits[1];
  for (const word of TRAILING_WORDS) {
    if (domain.toLowerCase().endsWith(word)) domain = domain.slice(0, -word.length);
  }
  domain = domain.replace(/[^a-zA-Z0-9.-]+$/, "");
  const domainParts = domain.split(".");
  if (domainParts.length >= 2) {
    let tld = domainParts[domainParts.length - 1];
    for (const word of TRAILING_WORDS) {
      if (tld.toLowerCase().endsWith(word)) tld = tld.slice(0, -word.length);
    }
    if (tld.length > 6) {
      for (const len of [4, 3, 2]) {
        const potential = tld.slice(0, len);
        if (/^[a-z]{2,4}$/i.test(potential)) { tld = potential; break; }
      }
    }
    domainParts[domainParts.length - 1] = tld;
    domain = domainParts.join(".");
  }
  let finalEmail = `${local}@${domain}`;
  for (const word of [...TRAILING_WORDS, "chatclick"]) {
    if (finalEmail.toLowerCase().endsWith(word))
      finalEmail = finalEmail.slice(0, -word.length).trim();
  }
  finalEmail = finalEmail.replace(/[^a-zA-Z0-9._%+-@]+$/, "");
  if (finalEmail.includes("@") && finalEmail.split("@")[1].includes(".")) {
    const parts = finalEmail.split("@");
    let cleaned = parts[1].replace(/[^a-zA-Z0-9.-]+$/, "");
    // Fix TLD with trailing characters (e.g., "comv" -> "com", "netx" -> "net")
    const domainParts = cleaned.split(".");
    if (domainParts.length >= 2) {
      let tld = domainParts[domainParts.length - 1];
      // If TLD is longer than 4 chars, try to extract valid 2-4 char TLD
      if (tld.length > 4 && !/^[a-z]{2,4}$/i.test(tld)) {
        for (const len of [4, 3, 2]) {
          const potentialTld = tld.slice(0, len);
          if (/^[a-z]{2,4}$/i.test(potentialTld)) {
            domainParts[domainParts.length - 1] = potentialTld;
            cleaned = domainParts.join(".");
            break;
          }
        }
      }
    }
    const result = `${parts[0]}@${cleaned}`.toLowerCase();
    return FINAL_EMAIL_VALIDATION.test(result) ? result : null;
  }
  return null;
}

/**
 * Filter raw emails into verified (official public contact) and rejected (with reason).
 * @param {string[]} rawEmails
 * @param {string} [websiteUrl] - For domain validation
 * @param {Set<string>} [fromMailto] - Emails from mailto: (confirmed in context)
 */
function filterAndClassifyEmails(rawEmails, websiteUrl, fromMailto = new Set()) {
  const verified = new Set();
  const rejected = [];
  const seen = new Set();

  for (let email of rawEmails) {
    if (!email || !email.includes("@")) continue;
    const normalized = normalizeEmail(email);
    if (!normalized) {
      rejected.push({ email: email.trim(), reason: "Invalid or malformed email" });
      continue;
    }
    if (seen.has(normalized)) continue;
    seen.add(normalized);

    const fromMailtoInContext = fromMailto.has(normalized);
    const { valid, reason } = validateOfficialContactEmail(normalized, websiteUrl, fromMailtoInContext);
    if (valid) {
      verified.add(normalized);
    } else {
      rejected.push({ email: normalized, reason: reason || "Not intended for public contact" });
    }
  }
  return {
    verified: [...verified],
    rejected,
  };
}

/** Legacy: returns verified emails only (for backward compat) */
function filterAndCleanEmails(rawEmails) {
  const { verified } = filterAndClassifyEmails(rawEmails);
  return verified;
}

function normalizeUrl(input) {
  let url = (input || "").trim();
  if (!url) return null;
  if (!url.startsWith("http://") && !url.startsWith("https://")) url = `https://${url}`;
  try {
    new URL(url);
    return url;
  } catch {
    return null;
  }
}

function doFetch(targetUrl, redirectCount = 0) {
  return new Promise((resolve) => {
    if (redirectCount >= 5) {
      resolve({ website: targetUrl, emails: [], verified: [], rejected: [], verifiedCount: 0, success: false, error: "Too many redirects" });
      return;
    }
    try {
      const parsedUrl = new URL(targetUrl);
      const client = parsedUrl.protocol === "https:" ? https : http;
      const path = (parsedUrl.pathname || "/") + (parsedUrl.search || "");

      const options = {
        hostname: parsedUrl.hostname,
        path: path || "/",
        method: "GET",
        rejectUnauthorized: false,
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en-US,en;q=0.5",
          "Accept-Encoding": "gzip, deflate, br",
        },
      };

      const req = client.request(options, (stream) => {
        const statusCode = stream.statusCode || 0;
        const location = stream.headers.location;

        if (statusCode >= 301 && statusCode <= 308 && location) {
          stream.destroy();
          const redirectUrl = location.startsWith("http")
            ? location
            : `${parsedUrl.protocol}//${parsedUrl.hostname}${location.startsWith("/") ? location : "/" + location}`;
          doFetch(redirectUrl, redirectCount + 1).then(resolve);
          return;
        }

        const chunks = [];
        const encoding = stream.headers["content-encoding"];

        stream.on("data", (chunk) => chunks.push(chunk));
        stream.on("end", () => {
          let data = Buffer.concat(chunks);
          if (encoding === "gzip") {
            try { data = zlib.gunzipSync(data); } catch (_) {}
          } else if (encoding === "deflate") {
            try { data = zlib.inflateSync(data); } catch (_) {}
          } else if (encoding === "br") {
            try { data = zlib.brotliDecompressSync(data); } catch (_) {}
          }
          const html = data.toString("utf8");
          const result = extractAndFilterEmails(html, targetUrl);
          const { verified, rejected, loadedViaJs, message } = result;
          // Detect when we should try Puppeteer: captcha/shell OR page has no email content (JS-rendered sites like upkeepdxb.com)
          const minHtmlLength = 2500;
          const looksLikeCaptchaOrShell =
            html.length < minHtmlLength ||
            /sgcaptcha|meta\s+http-equiv\s*=\s*["']refresh["'][^>]*content\s*=\s*["'][^"']*captcha/i.test(html);
          const visibleHtml = stripNonVisibleHtml(html);
          const hasNoEmailInSource =
            !/mailto:\s*[^"\s>]+@/i.test(html) &&
            !/[A-Za-z0-9._%+-]{1,64}@[A-Za-z0-9.-]{1,255}\.[A-Za-z]{2,}/.test(
              decodeHtmlEntities(deobfuscateEmailText(visibleHtml))
            );
          const needPuppeteerFallback =
            verified.length === 0 &&
            (looksLikeCaptchaOrShell || hasNoEmailInSource);
          const captchaRedirect =
            (stream.statusCode === 202 || stream.statusCode === 200) &&
            /sgcaptcha|meta\s+http-equiv\s*=\s*["']refresh["'][^>]*captcha/i.test(html);
          resolve({
            website: targetUrl,
            success: true,
            emails: verified,
            verified,
            rejected,
            verifiedCount: verified.length,
            ...(loadedViaJs && { loadedViaJs: true, message: message || "Emails present but require JS rendering" }),
            ...(needPuppeteerFallback && { needPuppeteerFallback: true }),
            ...(captchaRedirect && { captchaRedirect: true }),
          });
        });
      });

      const timeoutMs = parseInt(process.env.SCRAPE_TIMEOUT_MS || "30000", 10);

      req.on("error", (err) =>
        resolve({ website: targetUrl, emails: [], verified: [], rejected: [], verifiedCount: 0, success: false, error: err.message })
      );
      req.setTimeout(timeoutMs, () => {
        req.destroy();
        resolve({ website: targetUrl, emails: [], verified: [], rejected: [], verifiedCount: 0, success: false, error: "Request timeout" });
      });
      req.end();
    } catch (err) {
      resolve({ website: targetUrl, emails: [], verified: [], rejected: [], verifiedCount: 0, success: false, error: err.message });
    }
  });
}

/** Scan order: Homepage, then contact pages, about, support, legal. Each page HTML (incl. footer, header) is scanned for mailto: and explicit emails. */
const CRAWL_PATHS_ORDERED = [
  "/contact", "/contact-us", "/contact-exclusive-links", "/about", "/about-us", "/support",
  "/en/contact", "/iletisim", "/kontakt", "/contacto", "/help", "/destek",
  "/en/about", "/hakkimizda", "/ueber-uns",
  "/imprint", "/impressum", "/legal", "/privacy", "/gizlilik", "/kvkk",
];

const MAX_CRAWL_PAGES = parseInt(process.env.SCRAPE_MAX_CRAWL_PAGES || "10", 10);

/**
 * Scrape a single website by crawling relevant public pages and aggregating emails.
 * Crawls: main page + Contact (local language), About, Support, Legal/Imprint pages.
 * Inspects visible text only (ignores scripts, CSS, images, comments).
 * Accepts emails from any language.
 * @param {string} url - Website URL
 * @returns {Promise<{ website: string, success: boolean, emails: string[], verified: string[], rejected: Array<{ email: string, reason: string }>, error?: string }>}
 */
async function scrapeWebsite(url) {
  const targetUrl = normalizeUrl(url) || url;
  let parsed;
  try {
    parsed = new URL(targetUrl);
  } catch {
    return { website: targetUrl, success: false, emails: [], verified: [], rejected: [], verifiedCount: 0, error: "Invalid URL" };
  }

  const base = `${parsed.protocol}//${parsed.hostname}`;
  const urlsToCrawl = [targetUrl];
  for (const path of CRAWL_PATHS_ORDERED) {
    urlsToCrawl.push(base + path);
  }

  const allVerified = new Set();
  const allRejected = new Map();
  let atLeastOneSuccess = false;
  let anyLoadedViaJs = false;
  let anyCaptchaRedirect = false;
  const crawled = new Set();
  let pagesCrawled = 0;

  for (const crawlUrl of urlsToCrawl) {
    if (pagesCrawled >= MAX_CRAWL_PAGES) break;
    const norm = crawlUrl.replace(/\?.*$/, "").replace(/\/$/, "") || crawlUrl;
    if (crawled.has(norm)) continue;
    crawled.add(norm);
    pagesCrawled++;

    try {
      const result = await doFetch(crawlUrl);
      if (!result.success) continue;

      atLeastOneSuccess = true;
      if (result.loadedViaJs) anyLoadedViaJs = true;
      if (result.captchaRedirect) anyCaptchaRedirect = true;
      (result.verified || []).forEach((e) => allVerified.add(e));
      (result.rejected || []).forEach((r) => {
        if (!allRejected.has(r.email)) allRejected.set(r.email, r.reason);
      });
    } catch (_) {}
  }

  // Only return emails that are present on the site AND match the website domain.
  // Do not return wrong-domain emails (e.g. info@hadkaur.com on thetotalfitdubai.com).
  // Do not infer or invent emails; scrape only what is actually on the page.
  const websiteDomain = getWebsiteDomain(targetUrl);
  let verified = [];
  for (const e of allVerified) {
    const domain = e.split("@")[1];
    if (domain && emailDomainMatchesWebsite(domain, websiteDomain)) {
      verified.push(e);
    }
  }

  // Fallback: when no domain-matching email found, site may use a different domain for contact
  // (e.g. upkeepdxb.com shows upkeep@aaronz.co in Contact Us). Return those, excluding known template/footer domains.
  if (verified.length === 0 && allVerified.size > 0) {
    for (const e of allVerified) {
      const d = (e.split("@")[1] || "").toLowerCase();
      if (d && !TEMPLATE_DOMAINS_BLOCKLIST.includes(d)) verified.push(e);
    }
  }

  // When static fetch got no emails: try browser automation (Playwright first for captcha sites, then Puppeteer).
  const tryBrowser = verified.length === 0 && atLeastOneSuccess;
  const browserUrls = anyCaptchaRedirect
    ? [targetUrl, `${parsed.protocol}//${parsed.hostname}/contact`, `${parsed.protocol}//${parsed.hostname}/contact-us`, `${parsed.protocol}//${parsed.hostname}/about`]
    : [targetUrl];

  async function extractVerifiedFromBrowserHtml(html) {
    if (!html) return [];
    const jsResult = extractAndFilterEmails(html, targetUrl);
    let jsVerified = (jsResult.verified || []).filter((e) => {
      const domain = e.split("@")[1];
      return domain && emailDomainMatchesWebsite(domain, websiteDomain);
    });
    if (jsVerified.length === 0 && (jsResult.verified || []).length > 0) {
      jsVerified = (jsResult.verified || []).filter((e) => {
        const d = (e.split("@")[1] || "").toLowerCase();
        return d && !TEMPLATE_DOMAINS_BLOCKLIST.includes(d);
      });
    }
    return jsVerified;
  }

  if (tryBrowser) {
    // For captcha-protected sites (e.g. upkeepdxb.com): try Playwright first (often better at passing challenges).
    if (verified.length === 0 && anyCaptchaRedirect) {
      try {
        const { chromium } = require("playwright");
        const browser = await chromium.launch({
          headless: true,
          args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-blink-features=AutomationControlled"],
        });
        const context = await browser.newContext({
          viewport: { width: 1920, height: 1080 },
          userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          locale: "en-US",
        });
        for (const url of browserUrls) {
          if (verified.length > 0) break;
          try {
            const page = await context.newPage();
            await page.goto(url, { waitUntil: "domcontentloaded", timeout: 25000 });
            const waitForContentMs = 22000;
            const stepMs = 2000;
            let waited = 0;
            while (waited < waitForContentMs) {
              try {
                const currentUrl = page.url();
                if (!/sgcaptcha|captcha/i.test(currentUrl)) {
                  const hasContent = await page.evaluate(() => {
                    const hasMailto = !!document.querySelector('a[href^="mailto:"]');
                    const bodyText = document.body?.innerText || "";
                    return hasMailto || /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/.test(bodyText);
                  });
                  if (hasContent) break;
                }
              } catch (_) {}
              await new Promise((r) => setTimeout(r, stepMs));
              waited += stepMs;
            }
            await new Promise((r) => setTimeout(r, 2000));
            const html = await page.content().catch(() => "");
            await page.close().catch(() => {});
            const found = await extractVerifiedFromBrowserHtml(html);
            if (found.length > 0) verified = found;
          } catch (err) {
            if (process.env.SCRAPE_DEBUG === "1" || process.env.SCRAPE_DEBUG === "true") {
              console.warn("[emailScraper] Playwright failed for", url, err.message);
            }
          }
        }
        await context.close().catch(() => {});
        await browser.close().catch(() => {});
      } catch (err) {
        if (process.env.SCRAPE_DEBUG === "1" || process.env.SCRAPE_DEBUG === "true") {
          console.warn("[emailScraper] Playwright not available or launch failed:", err.message);
        }
      }
    }

    // Puppeteer fallback (or first try when not captcha).
    if (verified.length === 0) {
      for (const puppeteerUrl of browserUrls) {
        if (verified.length > 0) break;
        try {
          const puppeteer = require("puppeteer");
          const browser = await puppeteer.launch({
            headless: true,
            args: [
              "--no-sandbox",
              "--disable-setuid-sandbox",
              "--disable-dev-shm-usage",
              "--disable-gpu",
              "--disable-blink-features=AutomationControlled",
              "--window-size=1920,1080",
            ],
          });
          const page = await browser.newPage();
          await page.setViewport({ width: 1920, height: 1080 });
          await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
          await page.setExtraHTTPHeaders({ "Accept-Language": "en-US,en;q=0.9" });
          await page.evaluateOnNewDocument(() => {
            Object.defineProperty(navigator, "webdriver", { get: () => false });
          });
          await page.goto(puppeteerUrl, { waitUntil: "domcontentloaded", timeout: 25000 });
          const waitForContentMs = 20000;
          const stepMs = 2000;
          let waited = 0;
          while (waited < waitForContentMs) {
            try {
              const url = page.url();
              if (!/sgcaptcha|captcha/i.test(url)) {
                const hasContent = await page.evaluate(() => {
                  const hasMailto = !!document.querySelector('a[href^="mailto:"]');
                  const bodyText = document.body?.innerText || "";
                  const hasEmail = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/.test(bodyText);
                  return hasMailto || hasEmail;
                });
                if (hasContent) break;
              }
            } catch (_) {}
            await new Promise((r) => setTimeout(r, stepMs));
            waited += stepMs;
          }
          await new Promise((r) => setTimeout(r, 1500));
          const html = await page.content().catch(() => "");
          await browser.close().catch(() => {});
          const found = await extractVerifiedFromBrowserHtml(html);
          if (found.length > 0) verified = found;
        } catch (err) {
          if (process.env.SCRAPE_DEBUG === "1" || process.env.SCRAPE_DEBUG === "true") {
            console.warn("[emailScraper] Puppeteer failed for", puppeteerUrl, err.message);
          }
        }
      }
    }
  }

  const rejected = [...allRejected.entries()].map(([email, reason]) => ({ email, reason }));

  let errorMsg;
  if (verified.length === 0 && anyLoadedViaJs) {
    errorMsg = "Emails present but require JS rendering";
  } else if (verified.length === 0 && anyCaptchaRedirect) {
    errorMsg = "Site protected by captcha (e.g. SiteGround); could not extract emails";
  }

  return {
    website: targetUrl,
    success: atLeastOneSuccess,
    emails: verified,
    verified,
    rejected,
    ...(verified.length === 0 && anyLoadedViaJs && { loadedViaJs: true, error: errorMsg }),
    ...(verified.length === 0 && anyCaptchaRedirect && !anyLoadedViaJs && { error: errorMsg }),
    verifiedCount: verified.length,
  };
}

/**
 * Scrape multiple websites.
 * @param {string[]} websites - Array of URLs
 * @returns {Promise<Array<{ website: string, emails: string[], success: boolean, error?: string }>>}
 */
async function scrapeWebsites(websites) {
  const promises = websites.map((url) => scrapeWebsite(url));
  return Promise.all(promises);
}

module.exports = {
  scrapeWebsite,
  scrapeWebsites,
};
